# Generated by Django 5.2.7 on 2025-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('op_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_days', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
